name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }} for Client
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Client
        working-directory: ./client
        run: npm run build --if-present

      - name: Test Client
        working-directory: ./client
        run: npm test --if-present

      - name: Setup Node.js ${{ matrix.node-version }} for Server
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Build Server
        working-directory: ./server
        run: npm run build --if-present

      - name: Test Server
        working-directory: ./server
        run: npm test --if-present
