name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # ----- Client Steps -----
    - name: Install client dependencies
      working-directory: ./ll/client
      run: npm ci

    - name: Build client
      working-directory: ./ll/client
      run: npm run build --if-present

    - name: Test client
      working-directory: ./ll/client
      run: npm test --if-present

    # ----- Server Steps -----
    - name: Install server dependencies
      working-directory: ./ll/server
      run: npm ci

    - name: Build server
      working-directory: ./ll/server
      run: npm run build --if-present

    - name: Test server
      working-directory: ./ll/server
      run: npm test --if-present
